const data = [
  {
    id: 1,
    title: "ENS Linked",
    sub: "ENS Linked",
    image: require("../media/5.png"),
    val: "1.82 ^",
    name: "dingaling.eth",
    time: "2 months ago",
    col: "rgba(75, 223, 255, 1)",
    xp: "+200xp",
  },
  {
    id: 2,
    title: "Best FLip",
    sub: "Sold",
    image: require("../media/Rectangle2.png"),
    val: "98.5 ^",
    name: "CryptoPunk #2131",
    time: "10 days ago",
    col: "rgba(255, 193, 72, 1)",
    xp: "+150xp",
  },
  {
    id: 3,
    title: "Should have sold",
    sub: "Mint",
    name: "Rare Apepe #6974",
    image: require("../media/Rectangle3.png"),
    val: "1.82 ^",
    col: "rgba(68, 255, 200, 1)",
    time: "10 days ago",
    xp: "+200xp",
  },
  {
    id: 4,
    title: "First NFT bought",
    sub: "Bought",
    name: "BAYC #7925",
    image: require("../media/Rectangle4.png"),
    val: "1.82 ^",
    col: "rgba(75, 223, 255, 1)",
    time: "10 days ago",
    xp: "+200xp",
  },
  {
    id: 5,
    title: "Paper Handed",
    sub: "Sold",
    name: "Moonbird #7866",
    image: require("../media/Rectangle5.png"),
    val: "1.82 ^",
    col: "rgba(68, 255, 200, 1)",
    time: "10 days ago",
    xp: "+200xp",
  },
];
export default data;
