const more_data = [
  {
    id: 1,
    title: "Azuki #9839",
    sub: "ENS Linked",
    image: require("../media/NFT.png"),
    val: "02.82^",
    name: "Bought",
    time: "3 months",
    floor: "Floor",
    col: "rgba(75, 223, 255, 1)",
    xp: "+21.6%",
    val2: "12.74 ^",
  },
  {
    id: 2,
    title: "MAYC #9839",
    sub: "Sold",
    image: require("../media/NFT2.png"),
    val: "98.5 ^",
    time: "3 months",
    name: "Bought",
    floor: "Floor",
    col: "rgba(255, 193, 72, 1)",
    xp: "+150xp",
    val2: "12.74 ^",
  },
  {
    id: 3,
    title: "MoonBirds #9839",
    sub: "Mint",
    image: require("../media/NFT3.png"),
    name: "Bought",
    val: "02.82^",
    floor: "Floor",
    col: "rgba(68, 255, 200, 1)",
    time: "3 months",
    xp: "+21.6%",
    val2: "12.74 ^",
  },
  {
    id: 4,
    title: "Otherdeed #9839",
    sub: "Bought",
    image: require("../media/NFT4.png"),
    name: "Bought",
    val: "02.82^",
    floor: "Floor",
    col: "rgba(75, 223, 255, 1)",
    time: "3 months",
    xp: "+21.6%",
    val2: "12.74 ^",
  },
  {
    id: 5,
    title: "Cryptoz #9839",
    sub: "Sold",
    image: require("../media/NFT5.png"),
    name: "Bought",
    val: "02.82^",
    floor: "Floor",
    col: "rgba(68, 255, 200, 1)",
    time: "3 months",
    val2: "12.74 ^",
    xp: "+21.6%",
  },
];
export default more_data;
